#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
}

$monitor = new \ServiceMonitor\Slack\SlackMonitor(getenv('SLACK_TOKEN'));

$event = new class extends \ServiceMonitor\Slack\SlackEvent {
    public function isExecutable(array $value): bool { return true; }
    // All events execute

    public function execute(array $value): void
    {
        echo('--- New Event has arrived :) --- ' . PHP_EOL);
        dump($value);
    }
};

$monitor->setEvent($event);
echo 'Start monitoring.' . PHP_EOL;
$monitor->start();
