#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
}

$monitor = new \ServiceMonitor\Slack\SlackMonitor(getenv('SLACK_TOKEN'));
$monitor->setEvent(new \ServiceMonitor\Slack\SampleEvent());
echo 'Start monitoring.' . PHP_EOL;
$monitor->start();
